/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LED_green_aliases.h"
#include "LED_green.h"
#include "LED_orange_aliases.h"
#include "LED_orange.h"
#include "LED_red_aliases.h"
#include "LED_red.h"
#include "Push_Button_aliases.h"
#include "Push_Button.h"
#include "ErikaOS_ee.h"
#include "ErikaOS_ee_tracing.h"
#include "UART_LOG.h"
#include "isr_UART_Rx.h"
#include "WaveDAC8.h"
#include "ADC_DelSig.h"
#include "isr_DMA_ADC_MEM.h"
#include "isr_pushButton.h"
#include "DMA_ADC_MEM_dma.h"
#include "DMA_MEM_UART_dma.h"
#include "isr_DMA_MEM_UART.h"
#include "Clock_DMA_MEM_UART.h"
#include "DAC_Out_aliases.h"
#include "DAC_Out.h"
#include "ADC_In_aliases.h"
#include "ADC_In.h"
#include "UART_LOG_IntClock.h"
#include "WaveDAC8_DacClk.h"
#include "WaveDAC8_Wave1_DMA_dma.h"
#include "WaveDAC8_Wave2_DMA_dma.h"
#include "WaveDAC8_VDAC8.h"
#include "ADC_DelSig_AMux.h"
#include "ADC_DelSig_Ext_CP_Clk.h"
#include "ADC_DelSig_IRQ.h"
#include "ADC_DelSig_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

